### ISSUE TITLE
decide about including times

### ISSUE THREAD

**Issue by ajschumacher** [thisismetis/dsprework#10]
Hi @laumontemayor! I currently think we shouldn't include times for these tasks, but I'm curious to know your reasoning.

My thinking is that setting a time like "30 minutes to learn your editor" will be really frustrating for somebody who doesn't know an editor and wants to learn one properly, which could easily take a full day just to get started, and at the same time suggesting that time is condescending to somebody who already knows an editor well. Similarly, I want to suggest that people read Pro Git if they have time, and that is not the kind of thing you can do in 1 or 1.5 hours. If I have a degree in stats, I might spend very little time on the stats materials, etc.

I don't think the times would be helpful to me as a learner, and I recommend we take them out. What do you think?

**Comment by ajschumacher** [comment]
Just as another example, I'm pretty sure a lot of people spend a good deal more than two hours on the stats exercises, and I don't want them to think that that's bad.

**Comment by lauraxm** [comment]
@ajschumacher Great point. Everything depends on people's levels, motivation, energy etc. Let's remove! (I'll do it and submit the PR). 

I think the only thing we should agree on is how much time total the whole pre-work should take - this is mostly so students can plan ahead (especially the ones that are working right up until Metis). Does 30 - 40 hours sound reasonable? Too much? I'm afraid if the number is too small, people might wait until last minute.

**Comment by ajschumacher** [comment]
@laumontemayor's back! @laumontemayor's back! :tada: :bell: :cake: :tada:

**Comment by ajschumacher** [comment]
Let's say 40? That positions it as a solid week of work, or still a lot of work spread out across multiple weeks.

**Comment by ajschumacher** [comment]
closing! :door:
