### ISSUE TITLE
remove references to Metis internals?

### ISSUE THREAD

**Issue by ajschumacher** [thisismetis/dsprework#11]
Hi @laumontemayor! I think we should probably not refer to Metis internal resources like our Slack and Discourse in these materials, because they're public. Also, I think we shouldn't have references to Discourse anywhere, because we aren't going to use it any more. What do you think?

**Comment by lauraxm** [comment]
Hi @ajschumacher! You're right - we can mention Slack in the pre-work email anyway instead. And :+1: on removing references to Discourse! When is it officially going to stop being used? For the summer class or Fall?

**Comment by ajschumacher** [comment]
I think Discourse is kind of unofficially already not being used; some people from summer have gotten signed up for it, which is fine, but I'm not really seeing us putting stuff up there.

**Comment by ajschumacher** [comment]
not patient enough to wait for merge into master or whatever; closing now
