### ISSUE TITLE
consensus on text response format

### ISSUE THREAD

**Issue by ajschumacher** [thisismetis/dsprework#15]
Hi! @laumontemayor @podopie Will this work? I put in two spots in [03-editors.md](https://github.com/thisismetis/dsprework/blob/newgit/03-editors.md) for people to fill in. Is there a better way to have such question/response sections?

``` text

---

What terminal editor will you use? How did you make your decision?

REPLACE THIS TEXT WITH YOUR RESPONSE

---
```

**Comment by ajschumacher** [comment]
Hmm I'll put a couple more in; can change without too much trouble if need be.

**Comment by lauraxm** [comment]
@ajschumacher I think that works great! That way we avoid the headache of trying to find answers. The clearer the better!

**Comment by ajschumacher** [comment]
woot close~
