### ISSUE TITLE
drastically simplify the install step

### ISSUE THREAD

**Issue by ajschumacher** [thisismetis/dsprework#6]

**Comment by ajschumacher** [comment]
I think it's going to make sense to switch over to Anaconda. @podopie that's what you've used with GA courses, right? I think it's probably worth it for the class. We haven't been doing virtualenvs in the class at all. Maybe we should?

(Also Aaron Meurer from Continuum is always telling me I should use conda when I complain about pip on twitter.)

**Comment by podopie** [comment]
@ajschumacher Anaconda is very straightforward and I see it often enough in "real world" that it'd make sense here. I'd find it more important to explain package management and virtualenv in the context of anaconda (cost/benefit of using a different python install separate from your system install, for example). 

Honestly it's not that difficult to set up the majority of libraries using a brew'd version of Python and pip, but this only targets Mac users, and we shouldn't be depending on that.

p.s. Vi for life!

**Comment by ajschumacher** [comment]
Yeah I wonder if we should develop some materials about package management / development. For now, check out the new simplified install directions. So simple!

We should have some sort of editor competition.
